const data2 = {
    restaurants:[
        {
            id:1,
            title: 'Order, Reservation', 
            foodTitle:'Fried Chicken',
            street: ' District 1, Ho Chi Minh City',
            open:'Opening Hours: Today * 09.00 ~ 22.00',
            price: 'Price Range: $ 500VND/person',
            img:"./assets/img/food-13.png",
            
          },
          {
            id:2,
            title: 'Order, Reservation',
            foodTitle:'Fried Chicken',
            street: ' District 1, Ho Chi Minh City',
            open:'Opening Hours: Today * 09.00 ~ 22.00',
            price: 'Price Range: $ 500VND/person',
            img:"./assets/img/food-14.png",
          },
          {
            id:3,
            title: 'Order, Reservation',
            foodTitle:'Fried Chicken',
            street: ' District 1, Ho Chi Minh City',
            open:'Opening Hours: Today * 09.00 ~ 22.00',
            price: 'Price Range: $ 500VND/person',
            img:"./assets/img/food-14.png",
          },
          {
            id:4,
            title: 'Order, Reservation',
            foodTitle:'Fried Chicken',
            street: ' District 1, Ho Chi Minh City',
            open:'Opening Hours: Today * 09.00 ~ 22.00',
            price: 'Price Range: $ 500VND/person',
            img:"./assets/img/food-13.png",
          },
          {
            id:5,
            title: 'Order, Reservation',
            foodTitle:'Fried Chicken',
            street: ' District 1, Ho Chi Minh City',
            open:'Opening Hours: Today * 09.00 ~ 22.00',
            price: 'Price Range: $ 500VND/person',
            img:"./assets/img/food-14.png",
          },
          {
            id:6,
            title: 'Order, Reservation',
            foodTitle:'Fried Chicken',
            street: ' District 1, Ho Chi Minh City',
            open:'Opening Hours: Today * 09.00 ~ 22.00',
            price: 'Price Range: $ 500VND/person',
            img:"./assets/img/food-13.png",
          },
          {
            id:7,
            title: 'Order, Reservation',
            foodTitle:'Fried Chicken',
            street: ' District 1, Ho Chi Minh City',
            open:'Opening Hours: Today * 09.00 ~ 22.00',
            price: 'Price Range: $ 500VND/person',
            img:"./assets/img/food-14.png",
          },
          {
            id:8,
            title: 'Order, Reservation',
            foodTitle:'Fried Chicken',
            street: ' District 1, Ho Chi Minh City',
            open:'Opening Hours: Today * 09.00 ~ 22.00',
            price: 'Price Range: $ 500VND/person',
            img:"./assets/img/food-13.png",
          },
          {
            id:9,
            title: 'Order, Reservation',
            foodTitle:'Fried Chicken',
            street: ' District 1, Ho Chi Minh City',
            open:'Opening Hours: Today * 09.00 ~ 22.00',
            price: 'Price Range: $ 500VND/person',
            img:"./assets/img/food-14.png",
          },
          {
            id:10,
            title: 'Order, Reservation',
            foodTitle:'Fried Chicken',
            street: ' District 1, Ho Chi Minh City',
            open:'Opening Hours: Today * 09.00 ~ 22.00',
            price: 'Price Range: $ 500VND/person',
            img:"./assets/img/food-14.png",
          },
          {
            id:11,
            title: 'Order, Reservation',
            foodTitle:'Fried Chicken',
            street: ' District 1, Ho Chi Minh City',
            open:'Opening Hours: Today * 09.00 ~ 22.00',
            price: 'Price Range: $ 500VND/person',
            img:"./assets/img/food-14.png",
          },
          {
            id:12,
            title: 'Order, Reservation',
            foodTitle:'Fried Chicken',
            street: ' District 1, Ho Chi Minh City',
            open:'Opening Hours: Today * 09.00 ~ 22.00',
            price: 'Price Range: $ 500VND/person',
            img:"./assets/img/food-14.png",
          },
          {
            id:13,
            title: 'Order, Reservation',
            foodTitle:'Fried Chicken',
            street: ' District 1, Ho Chi Minh City',
            open:'Opening Hours: Today * 09.00 ~ 22.00',
            price: 'Price Range: $ 500VND/person',
            img:"./assets/img/food-14.png",
          },
    ]
}
export default data2;